// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Autin.Model;
//
//    var controlInfo = ControlInfo.FromJson(jsonString);

namespace Autin.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ControlInfo
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("param_name")]
        public string ParamName { get; set; }

        [JsonProperty("param_value")]
        public double ParamValue { get; set; }

        [JsonProperty("param_description")]
        public string ParamDescription { get; set; }

        [JsonProperty("client_id")]
        public long ClientId { get; set; }

        [JsonProperty("case_id")]
        public string CaseId { get; set; }
    }

    public partial class ControlInfo
    {
        public static List<ControlInfo> FromJson(string json) => JsonConvert.DeserializeObject<List<ControlInfo>>(json, Autin.Model.ControlInfoConverter.Settings);
    }

    public static class ControlInfoSerialize
    {
        public static string ToJson(this List<ControlInfo> self) => JsonConvert.SerializeObject(self, Autin.Model.ControlInfoConverter.Settings);
    }

    internal static class ControlInfoConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
