// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Autin.Model;
//
//    var powerLoad = PowerLoad.FromJson(jsonString);

namespace Autin.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class PowerLoad
    {
        [JsonProperty("case_id")]
        public string CaseId { get; set; }

        [JsonProperty("client_id")]
        public long ClientId { get; set; }

        [JsonProperty("settlement_date")]
        public DateTimeOffset SettlementDate { get; set; }
        
        [JsonProperty("id")]
        public double Id { get; set; }

        [JsonProperty("period_id")]
        public string PeriodId { get; set; }

        [JsonProperty("load_value")]
        public double Load { get; set; }

        [JsonProperty("node_id")]
        public string NodeId { get; set; }
    }

    public partial class PowerLoad
    {
        public static List<PowerLoad> FromJson(string json) => JsonConvert.DeserializeObject<List<PowerLoad>>(json, Autin.Model.PowerLoadConverter.Settings);
    }

    public static class PowerLoadSerialize
    {
        public static string ToJson(this List<PowerLoad> self) => JsonConvert.SerializeObject(self, Autin.Model.PowerLoadConverter.Settings);
    }

    internal static class PowerLoadConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
