// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Autin.Model;
//
//    var systemTotalLoss = SystemTotalLoss.FromJson(jsonString);

namespace Autin.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SystemTotalLoss
    {
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        [JsonProperty("period_id")]
        public string PeriodId { get; set; }

        [JsonProperty("system_total_loss")]
        public long SystemTotalLossSystemTotalLoss { get; set; }

        [JsonProperty("client_id")]
        public long ClientId { get; set; }

        [JsonProperty("case_id")]
        public string CaseId { get; set; }

        [JsonProperty("settlement_date")]
        public DateTimeOffset SettlementDate { get; set; }
    }

    public partial class SystemTotalLoss
    {
        public static List<SystemTotalLoss> FromJson(string json) => JsonConvert.DeserializeObject<List<SystemTotalLoss>>(json, Autin.Model.SystemTotalLossConverter.Settings);
    }

    public static class SystemTotalLossSerialize
    {
        public static string ToJson(this List<SystemTotalLoss> self) => JsonConvert.SerializeObject(self, Autin.Model.SystemTotalLossConverter.Settings);
    }

    internal static class SystemTotalLossConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
