// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Autin.Model;
//
//    var unitStartPrice = UnitStartPrice.FromJson(jsonString);

namespace Autin.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UnitStartPrice
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("unit_id")]
        public string UnitId { get; set; }

        [JsonProperty("period_id")]
        public string PeriodId { get; set; }

        [JsonProperty("cold_start_cost")]
        public double ColdStartCost { get; set; }

        [JsonProperty("warm_start_cost")]
        public double WarmStartCost { get; set; }

        [JsonProperty("hot_start_cost")]
        public double HotStartCost { get; set; }

        [JsonProperty("client_id")]
        public long ClientId { get; set; }

        [JsonProperty("case_id")]
        public string CaseId { get; set; }

        [JsonProperty("settlement_date")]
        public DateTimeOffset SettlementDate { get; set; }
    }

    public partial class UnitStartPrice
    {
        public static List<UnitStartPrice> FromJson(string json) => JsonConvert.DeserializeObject<List<UnitStartPrice>>(json, Autin.Model.UnitStartPriceConverter.Settings);
    }

    public static class UnitStartPriceSerialize
    {
        public static string ToJson(this List<UnitStartPrice> self) => JsonConvert.SerializeObject(self, Autin.Model.UnitStartPriceConverter.Settings);
    }

    internal static class UnitStartPriceConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
