// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Autin.Model;
//
//    var unitInitialParam = UnitInitialParam.FromJson(jsonString);

namespace Autin.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UnitInitialParam
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("unit_id")]
        public string UnitId { get; set; }

        [JsonProperty("initial_power")]
        public double InitialPower { get; set; }

        [JsonProperty("initial_state")]
        public double InitialState { get; set; }

        [JsonProperty("initial_offtime")]
        public double InitialOfftime { get; set; }

        [JsonProperty("initial_ontime")]
        public double InitialOntime { get; set; }

        [JsonProperty("client_id")]
        public long ClientId { get; set; }

        [JsonProperty("case_id")]
        public string CaseId { get; set; }

        [JsonProperty("settlement_date")]
        public DateTimeOffset SettlementDate { get; set; }
    }

    public partial class UnitInitialParam
    {
        public static List<UnitInitialParam> FromJson(string json) => JsonConvert.DeserializeObject<List<UnitInitialParam>>(json, Autin.Model.UnitInitialParamConverter.Settings);
    }

    public static class UnitInitialParamSerialize
    {
        public static string ToJson(this List<UnitInitialParam> self) => JsonConvert.SerializeObject(self, Autin.Model.UnitInitialParamConverter.Settings);
    }

    internal static class UnitInitialParamConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
