// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Autin.Model;
//
//    var unitNode = UnitNode.FromJson(jsonString);

namespace Autin.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UnitNode
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("node_id")]
        public string NodeId { get; set; }

        [JsonProperty("generator_id")]
        public string GeneratorId { get; set; }

        [JsonProperty("is_linked")]
        public bool IsLinked { get; set; }

        [JsonProperty("client_id")]
        public long ClientId { get; set; }

        [JsonProperty("case_id")]
        public string CaseId { get; set; }

        [JsonProperty("settlement_date")]
        public DateTimeOffset SettlementDate { get; set; }
    }

    public partial class UnitNode
    {
        public static List<UnitNode> FromJson(string json) => JsonConvert.DeserializeObject<List<UnitNode>>(json, Autin.Model.UnitNodeConverter.Settings);
    }

    public static class UnitNodeSerialize
    {
        public static string ToJson(this List<UnitNode> self) => JsonConvert.SerializeObject(self, Autin.Model.UnitNodeConverter.Settings);
    }

    internal static class UnitNodeConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
