// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Autin.Model;
//
//    var unitPrice = UnitPrice.FromJson(jsonString);

namespace Autin.Model
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class UnitPrice
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("unit_id")]
        public string UnitId { get; set; }

        [JsonProperty("cost_id")]
        public long CostId { get; set; }

        [JsonProperty("period_id")]
        public string PeriodId { get; set; }

        [JsonProperty("block_start")]
        public double BlockStart { get; set; }

        [JsonProperty("block_end")]
        public double BlockEnd { get; set; }

        [JsonProperty("price")]
        public double Price { get; set; }

        [JsonProperty("net_cost")]
        public double NetCost { get; set; }

        [JsonProperty("inc_cost")]
        public double IncCost { get; set; }

        [JsonProperty("inc_cost_end")]
        public double IncCostEnd { get; set; }

        [JsonProperty("client_id")]
        public long ClientId { get; set; }

        [JsonProperty("case_id")]
        public string CaseId { get; set; }

        [JsonProperty("settlement_date")]
        public DateTimeOffset SettlementDate { get; set; }
    }

    public partial class UnitPrice
    {
        public static List<UnitPrice> FromJson(string json) => JsonConvert.DeserializeObject<List<UnitPrice>>(json, Autin.Model.UnitPriceConverter.Settings);
    }

    public static class UnitPriceSerialize
    {
        public static string ToJson(this List<UnitPrice> self) => JsonConvert.SerializeObject(self, Autin.Model.UnitPriceConverter.Settings);
    }

    internal static class UnitPriceConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
