// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using AutinPower.WPF.Models;
//
//    var networkConfigModel = NetworkConfigModel.FromJson(jsonString);

namespace AutinPower.WPF.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using Autin.Model;

    public partial class NetworkConfigModel : IAutinDataModel
    {
        public string Key { get; set; }
        public DateTimeOffset DataDate { get; set; }

        [JsonProperty("settlement_date")]
        public DateTimeOffset SettlementDate { get; set; }

        [JsonProperty("user_id")]
        public long UserId { get; set; }

        [JsonProperty("client_token")]
        public string ClientToken { get; set; }

        [JsonProperty("ab_limit")]
        public long AbLimit { get; set; }

        [JsonProperty("bc_limit")]
        public long BcLimit { get; set; }

        [JsonProperty("dc_limit")]
        public long DcLimit { get; set; }

        [JsonProperty("ed_limit")]
        public long EdLimit { get; set; }

        [JsonProperty("ea_limit")]
        public long EaLimit { get; set; }
    }

    public partial class NetworkConfigModel
    {
        public static NetworkConfigModel FromJson(string json) => JsonConvert.DeserializeObject<NetworkConfigModel>(json, AutinPower.WPF.Models.NetworkConfigModelConverter.Settings);
    }

    public static class NetworkConfigModelSerialize
    {
        public static string ToJson(this NetworkConfigModel self) => JsonConvert.SerializeObject(self, AutinPower.WPF.Models.NetworkConfigModelConverter.Settings);
    }

    internal static class NetworkConfigModelConverter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
